### ISSUE TITLE
Refactor color constants into separate files

### ISSUE THREAD

**Issue by AnshG714** [foxhatleo/panic-painter#4]
For consistency, we should avoid directly using Color constants in our code for the sake of consistency and ease of reuse in different parts of the codebase. 

Example:
```
void CanvasBlock::markLost() {
    _hoverAllowed = false;
    _bg->setColor(Color4(170, 46, 37));
}

void CanvasBlock::markDone() {
    _hoverAllowed = false;
    _bg->setColor(Color4(82, 178, 2));
}
```

This shouldn't be a huge thing but I believe would be useful regardless.

**Comment by foxhatleo** [comment]
The canvas will be completely redesigned anyways. This code will be thrown out for sure.
